language: node_js

node_js:
  - "8"
  - "10"

before_script:
  - npm run bootstrap -- --npm-client=yarn
  - npm run build
script: npm run bootstrap -- --npm-client=yarn
#after_success:
#  - npm run coveralls
